site_name: Jason Vriends
site_description: Welcome to my personal digital garden, where I share my knowledge on a wide range of topics, including health, technology, flight simulation, amateur radio, and Christianity. Unlike traditional blogging, where articles are written and forgotten, the posts in this garden are treated as plants in different stages of growth and care. Some may wither and fade away, while others will thrive and become a valuable source of ongoing knowledge for both myself and the community that visits.
site_author: Jason Vriends
site_url: https://thevriends.com/
repo_url: https://github.com/jasonvriends/kb
edit_uri: edit/main/docs/

nav:
  - Introduction: index.md
  - About: about.md
  - Contact: contact.md
  - Topics:
      - Technology:
          - Operating Systems:
              - Linux:
                  - technology/operating-systems/linux/almalinux.md
              - Windows:
                  - technology/operating-systems/windows/wsl.md
          - Containers:
              - technology/containers/podman.md
          - Coding:
              - technology/coding/git.md
              - Languages:
                  - technology/coding/languages/python.md
              - Frameworks:
                  - Python:
                      - technology/coding/frameworks/python/django.md
                      - technology/coding/frameworks/python/fastapi.md
                  - JavaScript:
                      - technology/coding/frameworks/javascript/react.md
                      - technology/coding/frameworks/javascript/angular.md
      - Christianity:
          - christianity/bible.md
          - Studies:
              - Psalm 23: christianity/study/psalm-23.md

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.integrate
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:jason@thevriends.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jasonvriends
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JasonVriends
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jasonvriends/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-0TZXM4XGFV

markdown_extensions:
  - tables
  - abbr
  - pymdownx.keys
  - mdx_truly_sane_lists
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - social
  - search
  - git-revision-date-localized:
      enable_creation_date: true

copyright: |
  <a href="https://github.com/jasonvriends" target="_blank" rel="noopener">Jason Vriends</a>
